project:
  type: website
  output-dir: docs

website:
  title: "Sarah Bikes Around"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/acebulsk
format:
  html:
    theme: vapor
    css: styles.css



